systems:
  host01:
    active: true
    name: Google
    description: Checks the main page of Google
    docs: https://wiki.mycompany.com/host01
    host: aivoicecleaner.com
    interval: 6
    warning: 10  
    timeout: 30    
    check: default
    group: production
